### ISSUE TITLE
cocaine h4's go white

### ISSUE THREAD

**Issue by higab85** [higab85/drugsandme-django#10]
cocaine>Dose and onset > How you take it matters

h4's **powdered cocaine** and **crack cocaine** are black, but go white when hovered, which makes them invisible on the white background. 

Where do we need the h4's going white when hovered on?

**Comment by meaghanli** [comment]
the drugs-sidebar-boxes need to go white when hovered on

**Comment by higab85** [comment]
fixed on commit 17d2962a4074cc70f4b4711ab5e120f1d79e815f
